export type FilterType = 'Todos' | 'América' | 'Europa' | 'Asia' | 'África';

export const CONTINENT_BY_COUNTRY_CODE: Record<string, FilterType> = {
  UY: 'América',
  URU: 'América',
  AR: 'América',
  ARG: 'América',
  BR: 'América',
  BRA: 'América',
  CL: 'América',
  CHI: 'América',
  MX: 'América',
  MEX: 'América',
  US: 'América',
  USA: 'América',
  CA: 'América',
  CAN: 'América',
  IT: 'Europa',
  ITA: 'Europa',
  FR: 'Europa',
  FRA: 'Europa',
  DE: 'Europa',
  GER: 'Europa',
  FRG: 'Europa',
  GB: 'Europa',
  ENG: 'Europa',
  SE: 'Europa',
  SWE: 'Europa',
  CH: 'Europa',
  SUI: 'Europa',
  ES: 'Europa',
  ESP: 'Europa',
  RU: 'Europa',
  RUS: 'Europa',
  KR: 'Asia',
  KOR: 'Asia',
  JP: 'Asia',
  JPN: 'Asia',
  ZA: 'África',
  RSA: 'África',
  QA: 'Asia',
  QAT: 'Asia',
};
