export type FilterType = 'Todos' | 'América' | 'Europa' | 'Asia' | 'África';

export const CONTINENT_BY_COUNTRY_CODE: Record<string, FilterType> = {
  UY: 'América',
  AR: 'América',
  BR: 'América',
  CL: 'América',
  MX: 'América',
  MEX: 'América',
  US: 'América',
  USA: 'América',
  CA: 'América',
  CAN: 'América',
  IT: 'Europa',
  FR: 'Europa',
  DE: 'Europa',
  GB: 'Europa',
  SE: 'Europa',
  CH: 'Europa',
  ES: 'Europa',
  RU: 'Europa',
  KR: 'Asia',
  JP: 'Asia',
  ZA: 'África',
  QA: 'Asia',
};
