export type FlagSize = 'sm' | 'md';

const FIFA_TO_ALPHA2: Record<string, string | null> = {
  AFG: 'af',
  ALB: 'al',
  ALG: 'dz',
  ASA: 'as',
  AND: 'ad',
  ANG: 'ao',
  AIA: 'ai',
  ATG: 'ag',
  ARG: 'ar',
  ARM: 'am',
  ARU: 'aw',
  AUS: 'au',
  AUT: 'at',
  AZE: 'az',
  BAH: 'bs',
  BHR: 'bh',
  BAN: 'bd',
  BRB: 'bb',
  BLR: 'by',
  BEL: 'be',
  BLZ: 'bz',
  BEN: 'bj',
  BER: 'bm',
  BHU: 'bt',
  BOL: 'bo',
  BIH: 'ba',
  BOT: 'bw',
  BRA: 'br',
  VGB: 'vg',
  BRU: 'bn',
  BUL: 'bg',
  BFA: 'bf',
  BDI: 'bi',
  CAM: 'kh',
  CMR: 'cm',
  CAN: 'ca',
  CPV: 'cv',
  CAY: 'ky',
  CTA: 'cf',
  CHA: 'td',
  CHI: 'cl',
  CHN: 'cn',
  TPE: 'tw',
  COL: 'co',
  COM: 'km',
  CGO: 'cg',
  COK: 'ck',
  CRC: 'cr',
  CRO: 'hr',
  CUB: 'cu',
  CUW: 'cw',
  CYP: 'cy',
  CZE: 'cz',
  DEN: 'dk',
  DJI: 'dj',
  DMA: 'dm',
  DOM: 'do',
  COD: 'cd',
  ECU: 'ec',
  EGY: 'eg',
  SLV: 'sv',
  ENG: 'gb-eng',
  EQG: 'gq',
  ERI: 'er',
  EST: 'ee',
  SWZ: 'sz',
  ETH: 'et',
  FRO: 'fo',
  FIJ: 'fj',
  FIN: 'fi',
  FRA: 'fr',
  GAB: 'ga',
  GAM: 'gm',
  GEO: 'ge',
  GER: 'de',
  GHA: 'gh',
  GIB: 'gi',
  GRE: 'gr',
  GRN: 'gd',
  GUM: 'gu',
  GUA: 'gt',
  GUI: 'gn',
  GNB: 'gw',
  GUY: 'gy',
  HAI: 'ht',
  HON: 'hn',
  HKG: 'hk',
  HUN: 'hu',
  ISL: 'is',
  IND: 'in',
  IDN: 'id',
  IRN: 'ir',
  IRQ: 'iq',
  ISR: 'il',
  ITA: 'it',
  CIV: 'ci',
  JAM: 'jm',
  JPN: 'jp',
  JOR: 'jo',
  KAZ: 'kz',
  KEN: 'ke',
  KOS: null,
  KUW: 'kw',
  KGZ: 'kg',
  LAO: 'la',
  LVA: 'lv',
  LBN: 'lb',
  LES: 'ls',
  LBR: 'lr',
  LBY: 'ly',
  LIE: 'li',
  LTU: 'lt',
  LUX: 'lu',
  MAC: 'mo',
  MAD: 'mg',
  MWI: 'mw',
  MAS: 'my',
  MDV: 'mv',
  MLI: 'ml',
  MLT: 'mt',
  MTN: 'mr',
  MRI: 'mu',
  MEX: 'mx',
  MDA: 'md',
  MNG: 'mn',
  MNE: 'me',
  MSR: 'ms',
  MAR: 'ma',
  MOZ: 'mz',
  MYA: 'mm',
  NAM: 'na',
  NEP: 'np',
  NED: 'nl',
  NCL: 'nc',
  NZL: 'nz',
  NCA: 'ni',
  NIG: 'ne',
  NGA: 'ng',
  PRK: 'kp',
  MKD: 'mk',
  NIR: 'gb-nir',
  NOR: 'no',
  OMA: 'om',
  PAK: 'pk',
  PLE: 'ps',
  PAN: 'pa',
  PNG: 'pg',
  PAR: 'py',
  PER: 'pe',
  PHI: 'ph',
  POL: 'pl',
  POR: 'pt',
  PUR: 'pr',
  QAT: 'qa',
  IRL: 'ie',
  ROU: 'ro',
  RUS: 'ru',
  RWA: 'rw',
  SKN: 'kn',
  LCA: 'lc',
  VIN: 'vc',
  SAM: 'ws',
  SMR: 'sm',
  STP: 'st',
  KSA: 'sa',
  SCO: 'gb-sct',
  SEN: 'sn',
  SRB: 'rs',
  SEY: 'sc',
  SLE: 'sl',
  SGP: 'sg',
  SVK: 'sk',
  SVN: 'si',
  SOL: 'sb',
  SOM: 'so',
  RSA: 'za',
  KOR: 'kr',
  SSD: 'ss',
  ESP: 'es',
  SRI: 'lk',
  SDN: 'sd',
  SUR: 'sr',
  SWE: 'se',
  SUI: 'ch',
  SYR: 'sy',
  TAH: 'pf',
  TJK: 'tj',
  TAN: 'tz',
  THA: 'th',
  TLS: 'tl',
  TOG: 'tg',
  TGA: 'to',
  TRI: 'tt',
  TUN: 'tn',
  TUR: 'tr',
  TKM: 'tm',
  TCA: 'tc',
  UGA: 'ug',
  UKR: 'ua',
  UAE: 'ae',
  USA: 'us',
  URU: 'uy',
  VIR: 'vi',
  UZB: 'uz',
  VAN: 'vu',
  VEN: 've',
  VIE: 'vn',
  WAL: 'gb-wls',
  YEM: 'ye',
  ZAM: 'zm',
  ZIM: 'zw',
  FRG: 'de',
  GDR: null,
  SCG: null,
  TCH: null,
  URS: null,
  YUG: null,
  ZAI: null,
};

const SUPPORTED_ALPHA2_CODES = new Set(
  [...Object.values(FIFA_TO_ALPHA2), 'gb'].filter((code): code is string => code !== null),
);

/**
 * Maps FIFA team codes to flag-icons alpha-2 classes.
 * Dissolved or unsupported nations intentionally return null and use the UI fallback.
 */
export const fifaToAlpha2 = (countryCode: string): string | null => {
  const normalized = countryCode.trim().toUpperCase();

  if (normalized.length === 2) {
    const alpha2Code = normalized.toLowerCase();
    return SUPPORTED_ALPHA2_CODES.has(alpha2Code) ? alpha2Code : null;
  }

  return FIFA_TO_ALPHA2[normalized] ?? null;
};

export const FLAG_DISPLAY_SIZE: Record<FlagSize, { width: number; height: number }> = {
  sm: { width: 18, height: 13 },
  md: { width: 24, height: 18 },
};
